### PR TITLE
feat: file based config for Kafka

### PR DESCRIPTION
**Pull request by danieldaviestelicent**

### CODE REVIEW

**Comment by rvesse** [comment]
@Greg-teli100 Just bear in mind we probably need two slightly different Kafka configuration files generated as Python using certs directly whereas Java wants Trust and Key stores

**Review by rvesse — APPROVED** [review]

**Comment by Greg-teli100** [comment]
> @Greg-teli100 Just bear in mind we probably need two slightly different Kafka configuration files generated as Python using certs directly whereas Java wants Trust and Key stores

Sure, we could perhaps add jks stores as additional properties on the same client and ca external secrets, so both are catered for using the same secret.

**Comment by rob-telicent** [comment]
There's potential to wrap all three of those  external secrets into 1 (may need TF changes)

Also we could put the CA-Certs into a configmap (by definition they are public so won't need a secret).

LGTM 👍

**Review by rob-telicent — APPROVED** [review]

**Review by Greg-teli100 — APPROVED** [review]

**Comment by rvesse** [comment]
> > @Greg-teli100 Just bear in mind we probably need two slightly different Kafka configuration files generated as Python using certs directly whereas Java wants Trust and Key stores
> 
> Sure, we could perhaps add jks stores as additional properties on the same client and ca external secrets, so both are catered for using the same secret.

As I understand it for Strimzi operator driven clusters you some of this stuff combined into a single secret - https://strimzi.io/docs/operators/latest/deploying#mtls_authentication - though the CA trust store is separate.

So even though we're not using Strimzi for our Dev clusters the closer we can make what we do look like what Strimzi would do then the easier it will be to document how customers should enable this on their clusters if they are using Strimzi

**Pull request merged**
